rpack:
 #Use - set it to false if api mode used
 use: true
 #Usecmd - register commands
 usecmd: true
 server:
  sendpack:
   #Host - '<protocol>://<ip or hostname>:<port>/'
   host: http://127.0.0.1:25530/
   #Interface ip
   ip: 0.0.0.0
   port: 25530
   backlog: 0
   #Connect timeout (in ms)
   timeout: 0
   #Allow connection only from ips that connected to MC server (may not work if proxy server used)
   strictaccess: true
   #Wait acception - true resourcepack download start only after resourcepack status accepted recieved, false - resourcepack status ignored, blocked - auto
   #waitacception: true
   #Token salt - recomended to replace this by random generated if clientside caching used
   tokensalt: PlaceHereARandomBase64StringIfClientCacheEnabled
  #Connect api to other instance
  connect:
   use: false
   #Interface ip
   ip: 0.0.0.0
   tls:
    use: false
    path: connectcert.p12
    password: passwordkey
   #Client used on bukkit by default
   client:
    #Remote server ip
    serverip: 0.0.0.0
    port: 25534
   #Server used on velocity by default
   server:
    #Remote client ip
    clientip: 0.0.0.0
    port: 25534
    backlog: 0
 resourcepack:
  #Size limit - max packed resourcepack size recomended values for specific versions (select the value for lowest version with which you can join the server): 1.7.10-1.15.2 '52428800', 1.16-1.17.1 '104857600', 1.18+ '262144000'
  sizelimit: 262144000
  cache:
   #Serverside caching - store all packed resourcepacks in ram
   server: true
   #Clientside caching - store resourcepacks clientside (up to 10)
   client: true
